### ISSUE TITLE
Adapt to Capella 7

### ISSUE THREAD

**Issue by etraisnel2** [eclipse-capella/capella-xhtml-docgen#239]
Adapt to new Capella M2 
Remove anything related to requirement that was extract to basic-vp

topic "CAPELLA_REQUIREMENT_EXTENSION " has been removed as associated code is now generated in basic-vp
any extension code can be contributed using "CAPELLA_ELEMENT_EXTENSION" instead

**Comment by jamilraichouni** [comment]
Hi @etraisnel2 , Capella 7 is releases. When is a compatible release for this extension expected to be released?
